<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        City::insert([
            ['name' => 'تبریز', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اسکو', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اهر', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آذرشهر', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بستان آباد', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بناب', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جلفا', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'چاراویماق', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خداآفرین', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تبریز', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سراب', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شبستر', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'عجب شیر', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کلیبر', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مراغه', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مرند', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ملکان', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'میانه', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'هریس', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'هشترود', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ورزقان', 'province_id' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ارومیه', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اشنویه', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بوکان', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'پلدشت', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'پیرانشهر', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تکاب', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'چالدران', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'چایپاره', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خوی', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سردشت', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سلماس', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شاهین دژ', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شوط', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ماکو', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مهاباد', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'میاندوآب', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نقده', 'province_id' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اردبیل', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بیله سوار', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'پارس آباد', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خلخال', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سرعین', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کوثر', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گرمی', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مشگین شهر', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نمین', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نیر', 'province_id' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اصفهان', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اردستان', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آران وبیدگل', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'برخوار', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تیران وکرون', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'چادگان', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خمینی شهر', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خوانسار', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خور و بیابانک', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دهاقان', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سمیرم', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شاهین شهرومیمه', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شهرضا', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فریدن', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فریدونشهر', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فلاورجان', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کاشان', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گلپایگان', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'لنجان', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مبارکه', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نایین', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نجف آباد', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نطنز', 'province_id' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کرج', 'province_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ساوجبلاغ', 'province_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'طالقان', 'province_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نظرآباد', 'province_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فردیس', 'province_id' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ایلام', 'province_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ایوان', 'province_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آبدانان', 'province_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دره شهر', 'province_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دهلران', 'province_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شیروان وچرداول', 'province_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ملکشاهی', 'province_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مهران', 'province_id' => 6, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بوشهر', 'province_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تنگستان', 'province_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جم', 'province_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دشتستان', 'province_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دشتی', 'province_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دیر', 'province_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دیلم', 'province_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کنگان', 'province_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گناوه', 'province_id' => 7, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تهران', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اسلامشهر', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بهارستان', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'پاکدشت', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'پیشوا', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دماوند', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رباط کریم', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ری', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شمیرانات', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شهریار', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فیروزکوه', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قدس', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ملارد', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ورامین', 'province_id' => 8, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شهرکرد', 'province_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اردل', 'province_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بروجن', 'province_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فارسان', 'province_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کوهرنگ', 'province_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کیار', 'province_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'لردگان', 'province_id' => 9, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بیرجند', 'province_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بشرویه', 'province_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'درمیان', 'province_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سرایان', 'province_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سربیشه', 'province_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فردوس', 'province_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قاینات', 'province_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نهبندان', 'province_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'طبس', 'province_id' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مشهد', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'باخرز', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بجستان', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بردسکن', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بینالود', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تایباد', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تخت جلگه', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تربت جام', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تربت حیدریه', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جغتای', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جوین', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'چناران', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خلیل آباد', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خواف', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خوشاب', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'درگز', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رشتخوار', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'زاوه', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سبزوار', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سرخس', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فریمان', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قوچان', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کاشمر', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کلات', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گناباد', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مه ولات', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نیشابور', 'province_id' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بجنورد', 'province_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اسفراین', 'province_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جاجرم', 'province_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شیروان', 'province_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فاروج', 'province_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گرمه', 'province_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مانه وسملقان', 'province_id' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اهواز', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'امیدیه', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اندیکا', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اندیمشک', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ایذه', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آبادان', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'باغ ملک', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'باوی', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بندرماهشهر', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بهبهان', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خرمشهر', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دزفول', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دشت آزادگان', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رامشیر', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رامهرمز', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شادگان', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شوش', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شوشتر', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گتوند', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'لالی', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مسجدسلیمان', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'هفتگل', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'هندیجان', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'هویزه', 'province_id' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'زنجان', 'province_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ابهر', 'province_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ایجرود', 'province_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خدابنده', 'province_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خرمدره', 'province_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'طارم', 'province_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ماهنشان', 'province_id' => 14, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سمنان', 'province_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دامغان', 'province_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شاهرود', 'province_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گرمسار', 'province_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مهدی شهر', 'province_id' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'زاهدان', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ایرانشهر', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'چابهار', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خاش', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دلگان', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'زابل', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'زهک', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سراوان', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سرباز', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سیب و سوران', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کنارک', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مهرستان-زابلی', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نیک شهر', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نیمروز', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'هامون', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'هیرمند', 'province_id' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شیراز', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ارسنجان', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'استهبان', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اقلید', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آباده', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بوانات', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'پاسارگاد', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جهرم', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خرامه', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خرم بید', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خنج', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'داراب', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رستم', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'زرین دشت', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سپیدان', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سروستان', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فراشبند', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فسا', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فیروزآباد', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قیروکارزین', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کازرون', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کوار', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گراش', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'لارستان', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'لامرد', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مرودشت', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ممسنی', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مهر', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نی ریز', 'province_id' => 17, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قزوین', 'province_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'البرز', 'province_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آبیک', 'province_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بویین زهرا', 'province_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تاکستان', 'province_id' => 18, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قم', 'province_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جعفریه', 'province_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دستجرد', 'province_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سلفچگان', 'province_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قنوات', 'province_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کهک', 'province_id' => 19, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سنندج', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بانه', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بیجار', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دهگلان', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دیواندره', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سروآباد', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سقز', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قروه', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کامیاران', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مریوان', 'province_id' => 20, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کرمان', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ارزوییه', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'انار', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بافت', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بردسیر', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بم', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جیرفت', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رابر', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'راور', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رفسنجان', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رودبارجنوب', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ریگان', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'زرند', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سیرجان', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شهربابک', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'عنبرآباد', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فاریاب', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فهرج', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قلعه گنج', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کهنوج', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کوهبنان', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'منوجان', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نرماشیر', 'province_id' => 21, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کرمانشاه', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اسلام آبادغرب', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'پاوه', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ثلاث باباجانی', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جوانرود', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دالاهو', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'روانسر', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سرپل ذهاب', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سنقر', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'صحنه', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قصرشیرین', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کنگاور', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گیلانغرب', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'هرسین', 'province_id' => 22, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'یاسوج', 'province_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'باشت', 'province_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بهمیی', 'province_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بویراحمد', 'province_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'چرام', 'province_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دنا', 'province_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کهگیلویه', 'province_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گچساران', 'province_id' => 23, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گرگان', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آزادشهر', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آق قلا', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بندرگز', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ترکمن', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رامیان', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'علی آباد', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کردکوی', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کلاله', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گالیکش', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گمیشان', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'گنبدکاووس', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مراوه تپه', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مینودشت', 'province_id' => 24, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رشت', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'املش', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آستارا', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آستانه اشرفیه', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بندرانزلی', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تالش', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رضوانشهر', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رودبار', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رودسر', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سیاهکل', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شفت', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'صومعه سرا', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فومن', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'لاهیجان', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'لنگرود', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ماسال', 'province_id' => 25, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خرم آباد', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ازنا', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'الیگودرز', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بروجرد', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'پلدختر', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دلفان', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دوره', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دورود', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سلسله', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کوهدشت', 'province_id' => 26, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ساری', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آمل', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بابل', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بابلسر', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بهشهر', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تنکابن', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جویبار', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'چالوس', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رامسر', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سوادکوه', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'عباس آباد', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فریدونکنار', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قائم شهر', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'محمودآباد', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'میاندورود', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نکا', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نور', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نوشهر', 'province_id' => 27, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اراک', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'آشتیان', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تفرش', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خمین', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خنداب', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'دلیجان', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'زرندیه', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ساوه', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'شازند', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فراهان', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کمیجان', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'محلات', 'province_id' => 28, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بندرعباس', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ابوموسی', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بستک', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بشاگرد', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بندرلنگه', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'پارسیان', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'جاسک', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'حاجی اباد', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خمیر', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رودان', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'سیریک', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'قشم', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'میناب', 'province_id' => 29, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'همدان', 'province_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اسدآباد', 'province_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بهار', 'province_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تویسرکان', 'province_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'رزن', 'province_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'فامنین', 'province_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'کبودرآهنگ', 'province_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ملایر', 'province_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'نهاوند', 'province_id' => 30, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'یزد', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'ابرکوه', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'اردکان', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بافق', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'بهاباد', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'تفت', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'خاتم', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'صدوق', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'مهریز', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'میبد', 'province_id' => 31, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
